### ISSUE TITLE
another suggestion (not an issue)

### ISSUE THREAD

**Issue by galeroy** [ivycat/posts-in-page#11]
Sorry, one more suggestion.

I'm wondering if adding these comments to the posts_loop_template.php file (or creating a shortcode for this) might also help people new to WordPress -  or just anyone who would like to include the post date below the entry title.

maybe modifying line 7...

```
<h2 class="entry-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
```

by adding this...

```
<h2 class="entry-title"><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
<-- To display the post date below the entry title, uncomment these lines -->
    <!-- <h6> -->
        <?php /* printf( get_the_date()); */?>
    <!-- </h6> -->
```

Thanks again

**Comment by sewmyheadon** [comment]
We're planning to ship a few alternate post template layouts.
