### ISSUE TITLE
WordPress 4.2.2 Categories

### ISSUE THREAD

**Issue by EddyParera** [ivycat/posts-in-page#33]
I have some issues about this new version of Wordpress with this plugin because my version has page categories and this plugin mixes it up. Which means it shows posts and pages. There is a Post Category that is equal to another Page Category, I don't know if this is the issue or not.

What I need to know is a way to get over this, with scripting or with another way to use it in the Dashboard.

Thanks in advance.

**Comment by sewmyheadon** [comment]
Hi @EddyParera,

I believe you should be able to fix this by specifying the post type in your shortcode:

`[ic_add_posts post_type='post'] `

Does that work for you?
