### ISSUE TITLE
template= fails when the template is in a subdirectory

### ISSUE THREAD

**Issue by nurikabe** [ivycat/posts-in-page#49]
Some themes like https://arraythemes.com/themes/lenscap-wordpress-theme/ put templates inside subidrectories.  Defining a template like so:

`[ic_add_posts category='Random' paginate='yes' template='template-parts/content-index.php']`

Fails the `if ( $template_file != get_stylesheet_directory() . '/' . $path_parts['filename'] . '.' . $path_parts['extension'])` conditional because `pathinfo` only considers the final part of the path for `'filename`.

**Comment by sewmyheadon** [comment]
Howdy @nurikabe and thanks for the issue!

You're exactly right. Our last security update forbids loading of templates from outside of the theme's root folder.

We're looking to see if we can change that to allow subfolders too.

Will report back.

Eric

**Comment by sewmyheadon** [comment]
Hi @nurikabe - Following up to let you know that we've patched this issue by adding the ability to collect your Posts in Page templates within your theme in a subdirectory named _posts-in-page_.

This feature is in version 1.4.0 which will drop after we've completed QA and patched one more issue. In the meantime, you can download and test from our [develop branch](https://github.com/ivycat/posts-in-page/tree/develop).

Let me know if you have any questions or feedback.

Cheers!
