### ISSUE TITLE
Message when there are no posts?

### ISSUE THREAD

**Issue by mathyoo** [ivycat/Posts-in-Page#50]
This is probably more of a feature request, but is there a way to display a message if there are no posts that match the args in the shortcode?

**Comment by sewmyheadon** [comment]
Howdy mathyoo,

Interestingly, we’ve got a new release coming soon with this feature documented in it, but it is available now in version 1.3.0

You can add the following argument to your shortcode:

`none_found="what to say when there's nothing to see"`

![pip_none_found](https://cloud.githubusercontent.com/assets/2308362/24624330/5d5413b6-1860-11e7-82ff-8d8c9854bc2c.png)

I hope that helps!
Eric
