### ISSUE TITLE
Wrap in a div

### ISSUE THREAD

**Issue by smitralph** [ivycat/posts-in-page#51]
It should be fairly simple to wrap the posts together in a div. It would help a lot to customize the styling. I'd do it myself, but then i'd loose the changes after updates, right?

**Comment by sewmyheadon** [comment]
Hi @smitralph - It is fairly simple to change the markup to suit your needs. Check out the pinned threads on the top of the [support forum](https://wordpress.org/support/plugin/posts-in-page) and you'll get the drift. 

In short, you copy the _posts_loop_template.php_ file from your plugin to your theme's root directory and modify as needed.

That way, when the plugin is updated your customization remains.

**Comment by smitralph** [comment]
Hi,

Thanks for your quickeply,

I am aware of the customization method by copying the php file, and did that. However, that file only works within the loop. 
What I meant was the ability to wrap the whole bunch in one div, so the entire section can be styled.

I managed this by adjusting your class-page-posts.php by changing the $output just before the loop.
From line 44, I changed this:

> if ( $page_posts->have_posts() ) { 
> 	while ( $page_posts->have_posts() ): 
> 		 $output .= self::add_template_part( $page_posts ); 
> 	 endwhile; 

into this:

> if ( $page_posts->have_posts() ) {
> 	$output .= '<div class="row ivycat-post">';
> 	while ( $page_posts->have_posts() ):
> 		$output .= self::add_template_part( $page_posts );
> 	endwhile;
> 	$output .= '</div>’;


So now have a wrapping <div> to select. As I said, it’s simple, but I don’t want to loose my changes when you update the plugin. I hop e you might consider adding this in a future update.

Sorry for the e-mail, I would have replied in GitHub but the thread was already closed.


Thanks again, kind regards,

Ralph

**Comment by sewmyheadon** [comment]
I see what you're saying: you want a div to wrap the entire output, not
just single posts. Not sure on this. We'll take a look and see if we can at
least provide a hook you can use.

[image: photo]
Eric Amundson
Web Strategist & Developer
P  253-237-1851
<253-237-1851?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
E  eric@ivycat.com  <eric@ivycat.com> W  https://ivycat.com
<https://ivycat.com?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

<http://www.facebook.com/ivycatweb?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<http://twitter.com/ivycatweb?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<http://www.linkedin.com/company/ivycat-web-services?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://plus.google.com/+ivycat?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
From our blog: 6 Ways to Automate Your E-commerce Site with WordPress
Plugins
<https://ivycat.com/6-ways-automate-e-commerce-site-wordpress-plugins/?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by sewmyheadon** [comment]
Hi @smitralph - 

There are filters for this I believe:

```
add_filter('posts_in_page_pre_loop','preloop');

function preloop($output){

   echo '<div class="row ivycat-post">';

}

add_filter('posts_in_page_post_loop','postloop');

function postloop($output){

   echo '</div>';

}
```

Produces something like:

```
<div class="row ivycat-post"><!-- NOTE: If you need to make changes to this file, copy it to your current theme's main

					directory so your changes won't be overwritten when the plugin is upgraded. -->

 

<!-- Start of Post Wrap -->

<div class="post hentry ivycat-post">

	<!-- This is the output of the post TITLE -->

	<h2 class="entry-title"><a href="http://mysite/slug/">Post Title</a></h2>



	<!-- This is the output of the EXCERPT -->

	<div class="entry-summary">

		<p>Excerpt content</p>

	</div>



	<!-- This is the output of the META information -->

	<div class="entry-utility">

		<span class="cat-links">

		<span class="entry-utility-prep entry-utility-prep-cat-links">Posted in</span> <a href="http://localhost/golfsquad/category/uncategorized/" rel="category tag">Uncategorized</a>                                             </span>

		<span class="meta-sep">|</span>

		<span class="comments-link"><a href="http://localhost/golfsquad/blimy/#respond">Leave a comment</a></span>

		<span class="meta-sep">|</span> <span class="edit-link"><a class="post-edit-link" href="http://localhost/golfsquad/wp-admin/post.php?post=43103&amp;action=edit">Edit</a></span> 
	</div>

</div>

<!-- // End of Post Wrap -->

</div>
```

So, you should be able to use that to inject your wrapping markup.

I hope that helps!

**Comment by sewmyheadon** [comment]
Closing this issue since it can be handled using existing filters.
