### ISSUE TITLE
Filter posts by date

### ISSUE THREAD

**Issue by mquintas** [ivycat/posts-in-page#52]
I made some changes in order to filter post in range date (from_date -> today) o (from_date -> to_date)

from_date -> today
`[ic_add_posts paginate='yes' post category='category1' from_date='01-01-2016']`

from_date -> to_date
`[ic_add_posts paginate='yes' post category='category1' from_date='01-01-2016' to_date='31-12-2016']
`
changes are `class-page-posts.php`
line (30) added date_query
```protected function set_default_args() {
		$this->args = array(
			'post_type'      => 'post',
			'post_status'    => 'publish',
			'orderby'        => 'date',
			'order'          => 'DESC',
			'paginate'       => false,
			'template'       => false,
			'label_next'     => __( 'Next', 'posts-in-page' ),
			'label_previous' => __( 'Previous', 'posts-in-page' ),
			'none_found'     => '',
			'date_query'      => '', //this lines is new
		);
	}
```

line 190 added this

```
if ( isset( $atts['from_date'] ) && isset( $atts['to_date'] )) {
			$r_from = explode( '-', $atts['from_date'] );
			$r_to = explode( '-', $atts['to_date'] );
			$this->args['date_query'] = array(
				array(
					'after'    => array(
								'year'  => $r_from[2],
								'month' => $r_from[1],
								'day'   => $r_from[0],
								),
					'before'    => array(
								'year'  => $r_to[2],
								'month' => $r_to[1],
								'day'   => $r_to[0],
								),
				'inclusive' => true,
				),
			);
		} else if ( isset( $atts['from_date'] )) {
			$r_from = explode( '-', $atts['from_date'] );
			$r_to = explode( '-', $atts['to_date'] );
			$this->args['date_query'] = array(
				array(
					'after'    => array(
								'year'  => $r_from[2],
								'month' => $r_from[1],
								'day'   => $r_from[0],
								),
				'inclusive' => true,
				),
			);
		}

```

**Comment by sewmyheadon** [comment]
Howdy @mquintas - thanks a bunch for posting this!

What do you think about adding a _relative_ date feature - something like:

```
from_date = "-1 week"
to_date = "-1 day"
```

Just thinking out loud here . . . I could see how relative dates would allow people to show the last three months of news in a particular section without having to worry about updating the dates.

Do you think it would be more appropriate as a separate argument altogether?

@anvilzephyr - Interested in your input here too.

**Comment by mquintas** [comment]
I think that option is already implemented.

check the `class-page-posts.php` around line 190

looks like it uses the "date" property in the shortcut.

date='today-1'  (today minus 1 day)
date='week-2'  (today minus 2 weeks)
date='month-1'  (today minus 1 month)
date='year-1'  (today minus 1 year)

This feature doesn't seem to be documented...

**Comment by sewmyheadon** [comment]
Hey @mquintas, I'm going to close this issue as I've incorporated your from_date and to_date arguments in the latest version of Posts in Page, version 1.4 - soon to be released and currently in the [development branch](https://github.com/ivycat/posts-in-page/tree/develop).

Thank you so much for the contribution!
