### ISSUE TITLE
Changes to plugin break CSS styling for pagination

### ISSUE THREAD

**Issue by tjdownes** [ivycat/posts-in-page#57]
Comparing v1.3.1 to v1.2.4, the css for the pagination links breaks due to the lack of classes. In v1.2.4 `paginate_links` added `pip-nav-prev` and `pip-nav-next` to the `li` elements. This is not the same behavior in v.1.3.1, making it difficult to properly style the links.

Also, as a matter of code cleanup, it seems that in v.1.3.1 for the `paginate_links` method, the `$page` and `$per_page` variables are unused and should be removed.

**Comment by sewmyheadon** [comment]
Howdy @tjdownes  - great catches and thank you for the pull request. I'll review and merge ASAP.

> Also, as a matter of code cleanup, it seems that in v.1.3.1 for the paginate_links method, the $page and $per_page variables are unused and should be removed.

I believe you're right. We'll take a look at this too.

**Comment by sewmyheadon** [comment]
Hi TJ,

I'm not spotting that we ever had these classes in 1.2.4, but I do think they're a great idea and will merge this pull request.

Thanks again!

**Comment by tjdownes** [comment]
@sewmyheadon, it appears you're right. I must have modified the plugin at some point, because my local files show those classes but the tagged version on the repo does not. My apologies. But yes, it will be a nice addition.

**Comment by sewmyheadon** [comment]
Cool. I've merged the request and will include it in the next release to .org. Thanks again!
