### ISSUE TITLE
Hide pagination bar when results do not exceed per page count

### ISSUE THREAD

**Issue by tjdownes** [ivycat/posts-in-page#59]
It seems the pagination element is unnecessary when the found posts does not exceed the per page count. Removing the element when it's not needed makes it much easier to deal with styling issues when the pagination bar is not needed.

**Comment by sewmyheadon** [comment]
Hi @tjdownes  - thanks for the issue and pull request. I agree that there's no need to show pagination if there's just one page. We'll review your request and add that feature soon.
