### ISSUE TITLE
Feature Request - Specific Index Insertion

### ISSUE THREAD

**Issue by alexander-morris** [ivycat/posts-in-page#63]
Love this project - one issue I run into frequently though is that multiple posts-in-page sets in the same page will have overlapping post IDs. One way to fix this would be to allow users to specify the index they'd like to display.

i.e. in a single page:
[ic_add_posts category="foo" index_start="0" showposts="3"]

and 
[ic_add_posts category="foo" index_start="3" showposts="3"]

Would not show any overlaps. The first would show posts 1-3, and the second would show posts 4-6.

I might try to take a stab at this one if I have some time but thought I'd share the idea just in case anyone else has any suggestions for how to achieve this functionality without a pull request :)

**Comment by sewmyheadon** [comment]
Howdy, Alexander, 

Great idea! 

I _think_ our `offset` argument accomplishes that. You can see it in the [Dev branch](https://github.com/ivycat/posts-in-page/tree/develop).

> [ic_add_posts offset='3'] - Displays posts after the offset. An offset='3' will show all posts from the 4th one back.

Honestly, I need to do just a bit more testing before we release this update to wordpress.org.

I'd love it if you download and give it a try and let us know what you think.

Cheers,
Eric

**Comment by sewmyheadon** [comment]
Howdy @alexander-morris - just a quick note to let you know that Posts in Page 1.4.0 is now out and it contains this feature request and I've tested it for your application and it works like a charm.

I'll close this for now but please holler if you have any other feedback, feature or pull requests, etc.

Cheers!
Eric
