### ISSUE TITLE
Issue with Pro Theme sections after updating to 1.4.0

### ISSUE THREAD

**Issue by flawi** [ivycat/posts-in-page#65]
Hi, 

I really appreciate the great work you are doing with _posts-in-page_. After a while using it without any issue, I now got an issue after the update to 1.4.0:

I'm using the [Pro Theme](https://theme.co/pro/), which uses [Cornerstone](https://theme.co/cornerstone/) as page builder. After updating to `1.4.0` all sections underneath the section using _posts-in-page_ are gone. I still can see them in Cornerstone, but not in the productive page. Also the page DOM has no elements for the missing sections. So, I assume that the HTML elements were not generated.

I'm using:
- Wordpress: 5.1
- Pro Theme: 2.5
- Posts in page: 1.4.0

Current mitigation:
- Push the section with _posts-in-page_ to the bottom of th page.

Thanks for your help,
René

PS: I'm happy to provide more information. But since I didn't encounter any error message, I'm not sure what I else I can share with you.

**Comment by sewmyheadon** [comment]
Hello @flawi - thanks for reporting this. We're looking into it.

In the meantime, can you roll your install back to [version 1.3.1](https://github.com/ivycat/posts-in-page/archive/1.3.1.zip)?

**Comment by flawi** [comment]
Sure that would be possible.

**Comment by sewmyheadon** [comment]
Thanks, @flawi - I'll let you know as soon as we've released a patched version.

**Comment by sewmyheadon** [comment]
Howdy @flawi - I've just pushed the 1.4.1 update to both this repo in GitHub and to [wordpress.org](https://wordpress.org/plugins/posts-in-page/) and it should fix a few issues.

When you have a few moments, will you back up your existing Posts in Page install and then update it to 1.4.1 and let me know how it goes? 

Thanks,
Eric

**Comment by flawi** [comment]
Hej @sewmyheadon, I'm really impressed how fast you provided the fix! I updated to 1.4.1 and it's again working like a charm!

Thank you very much,
René
