### ISSUE TITLE
Uncaught Error: [] operator not supported for strings in /...wp-content/plugins/posts-in-page/posts_in_page.php:61

### ISSUE THREAD

**Issue by aldelval** [ivycat/posts-in-page#71]
From error.log:

[24-Sep-2019 09:51:04 UTC] PHP Fatal error:  Uncaught Error: [] operator not supported for strings in .../wp-content/plugins/posts-in-page/posts_in_page.php:61

Plugin Version: 1.4.4
PHP Version 7.3.9-1+ubuntu16.04.1+deb.sury.org+1

**Comment by priyankpatel-multidots** [comment]
Hi @aldelval ,

Thanks for using our plugin. I tried to generate the issue in my fresh setup of WordPress 5.5.1 which is running on PHP 7.4.1 but it seems working fine for me.
Can you please provide more information on this so we can help you out here.

Regards,
Team Ivycat

**Comment by aldelval** [comment]
Well, since my post is one year old, you might have fixed it in the meantime. I haven't really checked, but it was a common error when switching to php 7.1+, see e.g https://wordpress.org/support/topic/fatal-error-uncaught-error-operator-not-supported-for-strings/

**Comment by priyankpatel-multidots** [comment]
Hi @aldelval ,
We appolozise for providing late reply on the ticket.
And I hope you applied the solution and resolved the error there.
Thanks,
Team Ivycat
