### ISSUE TITLE
How to prevent printing of title ?

### ISSUE THREAD

**Issue by beppe9000** [ivycat/posts-in-page#73]
I would like to print the post body but not the title.

**Comment by sewmyheadon** [comment]
Hi @beppe9000 - 

You can remove the title by tweaking the output template.

Please check out the pinned posts at the top of the [Support Forum](https://wordpress.org/support/plugin/posts-in-page/) for more info on how to do this.

I hope that helps!

**Comment by beppe9000** [comment]
Is it not possible to use a shortcode argument? It would be much cleaner...

**Comment by sewmyheadon** [comment]
Not at the moment you have to tweak the output template.

**Comment by beppe9000** [comment]
Ok, thanks. I see this was closed: if there is another issue to track this feature could you please link to it.
