### ISSUE TITLE
Looking for code to add separator between posts and add page breaks after a certain number of posts

### ISSUE THREAD

**Issue by Gazabyte** [ivycat/posts-in-page#77]
Hi, I'm just wondering if you have anything coded that I can add into the template or html to add separators between posts that are being displayed, as well as the ability to have a page break after displaying 10 or so articles?

Many thanks,

Gaz

**Comment by priyankpatel-multidots** [comment]
Hello Gazabyte,

You can copy the 'posts_loop_template.php' file from the plugin's template folder and paste it to your theme's root directory.
Now you can edit the code inside of this file as per your requirement. You can also rename the file.
Please do not forget to include the template name in the shortcode as shown below. 
`[ic_add_posts template='template-fine-name.php']`

Thank you for using the plugin,
Team Ivycat
