### ISSUE TITLE
Add exclude and include

### ISSUE THREAD

**Issue by sewmyheadon** [ivycat/Posts-in-Page#8]
User requested the ability to specifically include cherry-picked posts, or even exclude from a query.

**Comment by amallory** [comment]
Exclude is base functionality, just add the parameter exclude_ids= and follow it with a comma separated list of the posts to exclude i.e. exclude_ids='25,15'. As for adding specific posts we start bumping into a limitation of wp_query. With posts listed it will only pull those posts not add them in addition to. It's either you get all posts that meet the criteria or you get the specific listed posts (that also meet the criteria). We could probably rewrite the code to run a first pass of wp_query to pull a list of post_ids matching the results and then add the specific requested post_ids if they are not already in the list. But it would require two runs of wp_query to do it and a rethink of the logic used in the plugin.

I would want to see a use case to justify this modification.
